core: frontend: availableServicesTable: Add text informing about the page
bluerobotics/BlueOS-docker pull request #1361
Opened 2023-01-17 02:05 UTC by patrickelectric

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

2023-01-17 04:40 UTC, ES-Alexander requested changes
Basic explanation was good - I added a bit more to try to describe what someone could use that for.

I'm not sure what this looks like on the page. If possible it would be good to have similar styling between the description here and on other pages (e.g. NMEA Injector)

2023-01-17 04:40 UTC, ES-Alexander commented on core/frontend/src/components/scanner/availableServicesTable.vue
> +      name, webpage, REST API endpoint and swagger documentation per version.
```suggestion
      Shows all available services running on BlueOS, including the service port,
      name, webpage, REST API endpoint, and swagger documentation per version.
      
      API endpoint links provide direct manual access to the APIs, and can be used
      to test how a service responds to a given request.
```

2023-01-17 04:43 UTC, patrickelectric commented on core/frontend/src/components/scanner/availableServicesTable.vue
> +      name, webpage, REST API endpoint and swagger documentation per version.
Done.

2023-01-18 07:26 UTC, ES-Alexander approved these changes

2023-01-18 07:26 UTC, merged