Add suport for OCI manifests
bluerobotics/BlueOS-docker pull request #1387
Opened 2023-01-22 17:15 UTC by Williangalvani

We were getting `OCI manifest found, but accept header does not support OCI (Open Container Initiative) manifest` errors when trying to fetch latest master manifests. My guess is that we somehow are shipping the image (or at least the manifest) in a different container format now:
<img width="985" alt="Screenshot 2023-01-22 at 14 06 10" src="https://user-images.githubusercontent.com/4013804/213929557-25fdb477-2019-464f-9ed9-5d67e5de2c98.png">

The error message doesn't look particularly good. but I'm happy to have the additional data in there

fix #1368 
fix #1379

potentially replaces #1384 

tested both in an older master with local changes, and current master with local changes. it seems to work fine:

<img width="881" alt="Screenshot 2023-01-22 at 14 09 19" src="https://user-images.githubusercontent.com/4013804/213929613-4a5becaa-5fe0-46ad-aed2-d1976e2534e9.png">

solution was grabbed from https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/31127

2023-01-22 18:38 UTC, patrickelectric requested changes
Update appears to be not working

![image](https://user-images.githubusercontent.com/1215497/213933687-3dcb186d-fc7f-4576-8876-1134142e18ee.png)

2023-01-22 22:28 UTC, Williangalvani commented
the update button only shows up for the same tags. it compares the sha and if it is diferrent:
https://github.com/bluerobotics/BlueOS-docker/blob/master/core/frontend/src/components/version-chooser/VersionChooser.vue#L370-L378

that's why I mentioned the "local changes". I launched an older master in blueos and put the new code there to test.

2023-01-22 22:30 UTC, Williangalvani commented
oh. you probably took longer than 2 min with version chooser stopped and bootstrap reverted you to factory. btw

2023-01-23 19:23 UTC, patrickelectric approved these changes

2023-01-23 19:23 UTC, merged