Add option to remove services log files
bluerobotics/BlueOS-docker pull request #1431
Opened 2023-02-02 17:41 UTC by patrickelectric

2023-02-02 19:56 UTC, Williangalvani requested changes

2023-02-02 19:56 UTC, Williangalvani commented on core/frontend/src/components/app/SettingsMenu.vue
> +        url: `${API_URL}/services/remove_log`,
```suggestion
        url: `${API_URL}/settings/remove_log`,
```
![image](https://user-images.githubusercontent.com/4013804/216436210-c90cbbb6-3b4e-4979-9d23-1085f2a63be8.png)

2023-02-02 22:47 UTC, patrickelectric commented on core/frontend/src/components/app/SettingsMenu.vue
> +        url: `${API_URL}/services/remove_log`,
ctrl-c issue

2023-02-03 13:22 UTC, Williangalvani approved these changes

2023-02-03 13:22 UTC, merged