Dialog parameter
bluerobotics/BlueOS-docker pull request #1464
Opened 2023-02-10 18:53 UTC by patrickelectric

2023-02-13 22:37 UTC, Williangalvani requested changes

2023-02-13 22:37 UTC, Williangalvani commented on core/frontend/src/components/parameter-editor/ParameterEditor.vue
> +      console.log('>>>', this.edit_dialog)
debug logs and commented code

2023-02-13 22:37 UTC, Williangalvani commented on core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
> +                  "
I didn't know you could do multiline strings here, cool

2023-02-13 23:26 UTC, ES-Alexander approved these changes
This looks great - love it! :-)

Is the blinking reboot icon tied to pirate mode somehow, or are the pirate mode mentions in the tray menu stuff just to get the icon to show up in the header? The parameter editor is available in friendly mode, so the reboot icon should be too (it might already be fine) :-)

2023-02-13 23:40 UTC, Williangalvani commented on core/frontend/src/components/app/VehicleRebootMenu.vue
> +  name: 'PirateModeMenu',
```suggestion
  name: 'VehicleRebootMenu',
```

2023-02-13 23:40 UTC, Williangalvani commented on core/frontend/src/components/app/VehicleRebootMenu.vue
> +      this.$emit('vehicleRebootCalled', settings.is_pirate_mode)
this does look off

2023-02-15 12:28 UTC, patrickelectric commented on core/frontend/src/components/app/VehicleRebootMenu.vue
> +      this.$emit('vehicleRebootCalled', settings.is_pirate_mode)
It was for testing, removing

2023-02-15 12:31 UTC, patrickelectric commented
> This looks great - love it! :-)
> 
> Is the blinking reboot icon tied to pirate mode somehow, or are the pirate mode mentions in the tray menu stuff just to get the icon to show up in the header? The parameter editor is available in friendly mode, so the reboot icon should be too (it might already be fine) :-)

It was something that I did for internal test, forgot to remove it

2023-02-15 18:29 UTC, Williangalvani commented
can you fix this issue? when we type a number it immediately switches to the option:

https://user-images.githubusercontent.com/4013804/219120163-bacbbb35-15bb-489a-98d0-971e0873a06d.mov

it is pre-existent, but since you are working in this component =P

2023-02-15 19:31 UTC, patrickelectric commented
@Williangalvani check now

2023-02-15 19:57 UTC, Williangalvani approved these changes
nice!

2023-02-15 19:57 UTC, Williangalvani commented on core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
> +      for (let v = 0; 1 << v < this.param.value; v += 1) {
does this work for v>32?

2023-02-15 19:57 UTC, merged

2023-02-15 21:30 UTC, ES-Alexander commented
> it is pre-existent, but since you are working in this component =P

Lol, nice logic - shame I didn't think to recommend #1210 at the same time...

2023-02-15 21:35 UTC, patrickelectric commented
> > it is pre-existent, but since you are working in this component =P
> 
> Lol, nice logic @Williangalvani - shame I didn't think to recommend #1210 at the same time...

I'm not a fan of changing the scope of a PR since this can result on bigger changes and drag the PR merge time with it. That's one of the reasons that ArduPilot has a PR list hell.