core: frontend: Add SDP file download for UDP streams
bluerobotics/BlueOS-docker pull request #1473
Opened 2023-02-14 18:29 UTC by joaoantoniocardoso

![image](https://user-images.githubusercontent.com/5920286/218825528-7b087cf8-3f1e-42dc-8c86-711288ee1629.png)

2023-02-15 11:56 UTC, ES-Alexander approved these changes
LGTM :-)

Presumably the actual SDP is generated by mavlink-camera-manager and this part is just the frontend fetching it? :-)

2023-02-15 12:15 UTC, joaoantoniocardoso commented
> LGTM :-)
> 
> Presumably the actual SDP is generated by mavlink-camera-manager and this part is just the frontend fetching it? :-)

yep

2023-02-15 12:23 UTC, ES-Alexander commented
Nice! :-)

2023-02-15 12:26 UTC, patrickelectric requested changes

2023-02-15 12:26 UTC, patrickelectric commented on core/frontend/src/store/video.ts
> +          URL.revokeObjectURL(url)
You should use the [file-saver](https://www.npmjs.com/package/file-saver) library that's already available on the project

2023-02-15 18:39 UTC, patrickelectric requested changes
Not working here
![image](https://user-images.githubusercontent.com/1215497/219122162-a6254032-2a9b-49f6-89da-c07d1cfa39ef.png)

![image](https://user-images.githubusercontent.com/1215497/219122101-b14dbe93-ee4d-414b-9b0b-cfe4810099fe.png)

2023-02-15 21:12 UTC, patrickelectric commented
I can download the SDP file, but it's not running via VLC, with the network configuration pointing to the SDP URL and also once downloaded the SDP file and opening it in VLC.

2023-02-15 21:38 UTC, joaoantoniocardoso commented
> I can download the SDP file, but it's not running via VLC, with the network configuration pointing to the SDP URL and also once downloaded the SDP file and opening it in VLC.

my VLC is broken, but it is working with mpv, can you test it?

2023-02-16 13:38 UTC, joaoantoniocardoso commented
> > I can download the SDP file, but it's not running via VLC, with the network configuration pointing to the SDP URL and also once downloaded the SDP file and opening it in VLC.
> 
> my VLC is broken, but it is working with mpv, can you test it?

Fixed my VLC, its playing the downloaded SDP file.

Can you post here the content of the file you are getting from mavlink-camera-manager?

2023-02-16 15:21 UTC, patrickelectric approved these changes

2023-02-16 15:22 UTC, merged