Wip: motor test
bluerobotics/BlueOS-docker pull request #1499
Opened 2023-02-20 17:30 UTC by Williangalvani

needs some cleaning up, and probably refactoring the the arm button into a component

tested with a servo in the pwm rail and 5v jumped to it

2023-02-23 21:22 UTC, Williangalvani commented
change color of main bhar
make body transaprent in pwm outputs
look at cockpit's armed button

2023-03-02 18:38 UTC, Williangalvani commented
we still need to able to revert the motor direction, along with a couple of other things. I intend to do this as it's own component in another pr

2023-03-10 16:48 UTC, patrickelectric requested changes

2023-04-05 01:31 UTC, Williangalvani commented on core/frontend/src/store/mavlink.ts
> +      if (receivedMessage.header.component_id !== 1) {
removed it. I'm not sure of why it was there in the first place 🤔

2023-04-05 01:47 UTC, Williangalvani commented on core/frontend/src/components/vehiclesetup/PwmSetup.vue
> +      const percent = (value - 1500) / 10
motors don't use SERVOn_MIN/MAX

We can expose MOT_PWM_MIN/MAX in another slider, I think.

2023-04-06 13:09 UTC, Williangalvani commented on core/frontend/src/components/vehiclesetup/PwmSetup.vue
> +      const percent = (value - 1500) / 10
we don't really have TRIM params for motors, though 😅

2023-04-07 10:59 UTC, patrickelectric commented
@Williangalvani can you rebase over master ?

2023-04-07 13:25 UTC, patrickelectric commented on core/frontend/src/components/vehiclesetup/PwmSetup.vue
> +            target_system: 1,
That will be affect by #1581, do you prefer to merge it before ?

2023-04-07 13:26 UTC, patrickelectric commented on core/frontend/src/components/vehiclesetup/PwmSetup.vue
> +    transition: none;
the indentation of this css does not match with the others

2023-04-08 22:25 UTC, patrickelectric approved these changes

2023-04-08 22:25 UTC, merged