Do not show Wizard when BlueOS is down
bluerobotics/BlueOS-docker pull request #1610
Opened 2023-04-11 15:51 UTC by patrickelectric

2023-04-13 13:57 UTC, Williangalvani requested changes

2023-04-13 13:57 UTC, Williangalvani commented on core/frontend/src/components/wizard/Wizard.vue
> +    if (wizard !== undefined && wizard?.version !== WIZARD_VERSION) {
what is the logic here? is undefined for "unable to reach backend"? I think it deserves at least a comment

2023-04-13 13:57 UTC, Williangalvani commented on core/frontend/src/components/wizard/Wizard.vue
> +    const wizard = await bag.getData('wizard2')
why changing to "wizard2"?

2023-04-13 20:14 UTC, patrickelectric commented on core/frontend/src/components/wizard/Wizard.vue
> +    const wizard = await bag.getData('wizard2')
Oh, that was code to test the feature

2023-04-14 18:45 UTC, Williangalvani commented
fixes #1620 ?

2023-04-14 18:45 UTC, merged