core: frontend: wizard: add skip and disable options to wizard
bluerobotics/BlueOS-docker pull request #1746
Opened 2023-06-06 11:23 UTC by Williangalvani

<img width="734" alt="Screenshot 2023-06-06 at 00 00 50" src="https://github.com/bluerobotics/BlueOS-docker/assets/4013804/0295638b-24cf-4f70-951f-0c6d19151faa">

Skip is for the current session. Disable is until the next Wizard version change.

Not quire sure how I feel about this one 🤔

2023-06-06 12:17 UTC, joaoantoniocardoso requested changes
I think we should at least explain the implications and how to revert the action, when possible.

maybe change "Skip" to "Do later", and require a confirmation for "disable", with a tooltip like "I want to do the system configuration manually by myself", with a dialogue explaining something like "Disabling is not recommended, and will require manual configuration. Be sure to visit the firmware and vehicle pages. To enable the wizard again, a full settings reset is necessary."

2023-06-07 06:35 UTC, ES-Alexander commented
Agreed with @joaoantoniocardoso that it's not very clear what these do at the moment, and that explanatory tooltips are a good idea (possibly with a (?) icon to make it clear tooltips are available). Maybe we could change the names to "Ask Me Later" and "Leave Me Alone"/"I Know What I'm Doing" or something? Also, "Disable Wizard" just sounds brutal - poor wizard... 😂 

I also think that having two vehicles and two buttons makes it seem a bit like the buttons correspond to the vehicles, so maybe we should put both buttons on the same side, or put a horizontal separator line between the vehicle selector and the buttons or something.

2023-06-07 15:24 UTC, Williangalvani commented
> I would go for "Ask me later" and "Don't show again". Those are widely used, so users are already used to them.

I like it.

2023-06-07 19:43 UTC, rafaellehmkuhl approved these changes

2023-06-07 20:07 UTC, merged