Kraken: do not blindly filter extension before properly removing it
bluerobotics/BlueOS-docker pull request #1837
Opened 2023-06-28 19:43 UTC by Williangalvani

2023-06-28 19:45 UTC, patrickelectric approved these changes

2023-06-28 20:46 UTC, joaoantoniocardoso requested changes
It doesn't fix it:
![image](https://github.com/bluerobotics/BlueOS-docker/assets/5920286/be66750c-5a5c-4c7d-9d79-9f06a887523c)

2023-06-28 21:45 UTC, joaoantoniocardoso approved these changes

2023-06-28 21:46 UTC, joaoantoniocardoso requested changes
Ooops, wrong tab.

2023-06-28 22:35 UTC, joaoantoniocardoso commented
There's a null-check missing

![image](https://github.com/bluerobotics/BlueOS-docker/assets/5920286/49d4c1bb-b76f-4755-97c4-32a084285c2d)

2023-06-29 19:03 UTC, joaoantoniocardoso approved these changes

2023-06-29 19:03 UTC, merged