Add tooltips
bluerobotics/BlueOS-docker pull request #789
Opened 2022-02-11 15:18 UTC by rafaellehmkuhl

- Add tooltip-as-directive lib
- Add tooltips on EndpointCard

2022-02-11 19:42 UTC, Williangalvani requested changes
Nice! but can we have it show the current state of the thing?
so this ones should show "not protected" and "disabled":
![change](https://user-images.githubusercontent.com/4013804/153658728-ed71c783-ae39-455f-aa23-a2a86e9be07b.gif)

2022-02-14 11:43 UTC, rafaellehmkuhl commented
> Nice! but can we have it show the current state of the thing? so this ones should show "not protected" and "disabled": ![change](https://user-images.githubusercontent.com/4013804/153658728-ed71c783-ae39-455f-aa23-a2a86e9be07b.gif)

Oh, for sure haha

2022-02-14 13:26 UTC, patrickelectric commented on core/frontend/src/components/autopilot/EndpointCard.vue
> +                v-tooltip="endpoint.persistent ? 'Persistent' : 'Not persistent'"
Is there a way to force the usage of icons + tooltips for consistency ?

2022-02-15 12:35 UTC, patrickelectric approved these changes

2022-02-15 12:35 UTC, merged