core: cable-guy: More than one IP address
bluerobotics/BlueOS-docker pull request #797
Opened 2022-02-16 20:03 UTC by rafaellehmkuhl

Before this patch, cable-guy was only able to handle one address per ethernet interface. This was leading to issues like the user only being able to see one IP address on the frontend (even when the interface had multiple), which could cause some misunderstood.

With this patch, the user is now able to:
- See multiple IP addresses associated with each ethernet interface
- Add new IP addresses to a given interface
- Remove specific IP addresses from a given interface

<img width="546" alt="image" src="https://user-images.githubusercontent.com/6551040/154346502-01cc8779-f97d-44b8-998b-ec815f681faf.png">

Fix #428

2022-02-17 21:15 UTC, rafaellehmkuhl commented
> Is there a docker ?

Yup, same same as the branch

2022-02-18 06:51 UTC, patrickelectric requested changes
It's showing three IP blocks, but eth0 here only have 2
![image](https://user-images.githubusercontent.com/1215497/154631800-5f8c263f-fd2f-4400-80c2-c13a39066a3d.png)
![image](https://user-images.githubusercontent.com/1215497/154631817-c8c94d4f-ec52-4cae-b1b2-8af5db793350.png)

- It's appears possible to set a server DHCP, from the options but nothing happens. 
- When deleting an IP configuration, it still shows for a couple of seconds after finishing the update on the UI. 

When creating a new dynamic IP, more 3 IPs appears as IPv6 here.
![image](https://user-images.githubusercontent.com/1215497/154632612-7fbf50af-e81f-4a03-9809-4b891829f306.png)
![image](https://user-images.githubusercontent.com/1215497/154632561-a4bec82e-5f98-4c67-a1f4-494e60040301.png)

2022-02-18 14:34 UTC, rafaellehmkuhl commented on core/services/cable_guy/api/manager.py
> +            self.get_interface_by_name(interface_name)
It is, yes. Will add a comment.

2022-02-18 16:31 UTC, rafaellehmkuhl commented
Image updated with proper fixes.

2022-02-21 12:01 UTC, patrickelectric requested changes
Its failing to change to dynamic IP:
![image](https://user-images.githubusercontent.com/1215497/154951102-bbe40b46-18ae-4e67-8985-80ecd3a74e3c.png)

![image](https://user-images.githubusercontent.com/1215497/154951174-636c4ff6-9789-4bf9-85f1-abbcaf34f8b7.png)

![image](https://user-images.githubusercontent.com/1215497/154951102-bbe40b46-18ae-4e67-8985-80ecd3a74e3c.png)

The first link does not change to dynamic or a new dynamic is not added.
If we only support a single dynamic ip, we should remove the dynamic IP option and server option if they are already available.

2022-02-21 12:20 UTC, rafaellehmkuhl commented
> Its failing to change to dynamic IP: ![image](https://user-images.githubusercontent.com/1215497/154951102-bbe40b46-18ae-4e67-8985-80ecd3a74e3c.png)
> 
> ![image](https://user-images.githubusercontent.com/1215497/154951174-636c4ff6-9789-4bf9-85f1-abbcaf34f8b7.png)
> 
> ![image](https://user-images.githubusercontent.com/1215497/154951102-bbe40b46-18ae-4e67-8985-80ecd3a74e3c.png)
> 
> The first link does not change to dynamic or a new dynamic is not added. If we only support a single dynamic ip, we should remove the dynamic IP option and server option if they are already available.

Yes. I'm aiming with this patch to just support multiples IPs, but not change the manager behavior. I have a patch for the sequence that will do some behavior changes to make it clear to the user what's happening. Basically I changed the DHCP and Dynamic IP creation for a button allowing enabling/disabling DHCP server, as we support only one, and another button to "re-trigger" dynamic IP instead of "adding", as we don't control how many and which IPs the external DHCP server will send.

2022-02-21 19:53 UTC, patrickelectric approved these changes

2022-02-21 19:53 UTC, merged