core: ardupilot-manager: Support Pixhawk4 (+ other improvements)
bluerobotics/BlueOS-docker pull request #866
Opened 2022-03-09 21:05 UTC by rafaellehmkuhl

- Fully support Pixhawk4 (add support for firmware management and correct board detection);
- Allow toggling between different connected boards (specially useful for development and testing);
- Disallow firmware management for unsupported board (not Pixhawk1 nor Pixhawk4), preventing bad firmware uploads;
- Improve board detection, preventing bootloader from being as a fully booted board;
- Prevent ardupilot binaries being left running by pruning them all (and not only the one running);
- Make mavlink-router behavior more predictable by always asking for master-endpoint on start, preventing, for example, bad restarts from the watchdog;
- Make FlightController the central logic piece for ArdupilotManager, in place of Platform;

...and some other small code/logic improvements.

Fix #810
Fix #713
Fix #452
Fix #393

2022-03-09 21:11 UTC, rafaellehmkuhl commented
To notice: my first approach for the board differentiation was to use the board_id identification from the bootloader, which can be accomplished through `uploader.py`, but the script board identification showed not to be reliable enough, often hanging on the bootloader identification/reboot part. During tests, I found directly communicating with the firmware to be a more reliable approach. For the future, to support any board, this is a path to walk.

2022-03-14 16:19 UTC, patrickelectric requested changes

2022-03-14 16:20 UTC, rafaellehmkuhl commented on core/services/ardupilot_manager/ArduPilotManager.py
> +        await self.start_ardupilot()
The idea behind the `preferred_board` is to store the board between sessions.

2022-03-14 17:46 UTC, patrickelectric requested changes
![image](https://user-images.githubusercontent.com/1215497/158228559-4d63dca0-c4cd-45e6-9ea5-a014e9d49252.png)

I was unable to replicate but once the text "Px4 4.x" (or something closer to it) appeared over Pixhawk4.

2022-03-14 17:50 UTC, rafaellehmkuhl commented
> ![image](https://user-images.githubusercontent.com/1215497/158228559-4d63dca0-c4cd-45e6-9ea5-a014e9d49252.png)
> 
> I was unable to replicate but once the text "Px4 4.x" (or something closer to it) appeared over Pixhawk4.

Did you update the board firmware? From what I've check, the board we've received comes with PX4, not Ardupilot, and the original USB name is something like what you've mentioned.

2022-03-14 17:54 UTC, patrickelectric commented on core/services/ardupilot_manager/ArduPilotManager.py
> +        await self.start_ardupilot()
a setter can do the job, no problem.

2022-03-16 12:16 UTC, patrickelectric commented
@rafaellehmkuhl what is the status of this PR ?

2022-03-16 12:17 UTC, rafaellehmkuhl commented
> @rafaellehmkuhl what is the status of this PR ?

Just waiting approval.

2022-03-16 12:20 UTC, patrickelectric commented
> > @rafaellehmkuhl what is the status of this PR ?
> 
> Just waiting approval.

What about the discussion done in https://github.com/bluerobotics/BlueOS-docker/pull/866/files/83dd009c376005cbc302c39fc9c0016c2a3a0ead..e4126f6f5b25b26fc0ab5663c6ecc10ae4091f52#r826175880 ?

2022-03-16 12:23 UTC, rafaellehmkuhl commented
> > > @rafaellehmkuhl what is the status of this PR ?
> > 
> > 
> > Just waiting approval.
> 
> What about the discussion done in https://github.com/bluerobotics/BlueOS-docker/pull/866/files/83dd009c376005cbc302c39fc9c0016c2a3a0ead..e4126f6f5b25b26fc0ab5663c6ecc10ae4091f52#r826175880 ?

I had understood that you agreed to keep it as it was. 
Let me change it here, and I ping you.

2022-03-16 15:14 UTC, patrickelectric approved these changes

2022-03-16 15:14 UTC, merged