Add welcome tour
bluerobotics/BlueOS-docker pull request #890
Opened 2022-03-22 17:59 UTC by rafaellehmkuhl

2022-03-22 18:38 UTC, patrickelectric requested changes
The docker available is failing to run:
TypeError: Cannot read properties of undefined (reading 'welcomeTour')

2022-03-23 15:01 UTC, Williangalvani commented on core/frontend/src/libs/settings.ts
> +        throw new Error(`Tour version (${version}) is the same as in store (${store_tour_version}})`)
do we really need to throw an exception here? this is throwing when opening the page after first time.

2022-03-23 15:32 UTC, patrickelectric approved these changes

2022-03-23 15:33 UTC, Williangalvani approved these changes

2022-03-23 15:34 UTC, merged