core: frontend: views: NetworTestView: Move from await to finally
bluerobotics/BlueOS-docker pull request #944
Opened 2022-04-01 19:59 UTC by patrickelectric

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

2022-04-01 20:29 UTC, rafaellehmkuhl requested changes

2022-04-01 20:29 UTC, rafaellehmkuhl commented on core/frontend/src/views/NetworkTestView.vue
>      async checkUploadSpeed(): Promise<void> {
In this case, you don't need to declare the method as asynchronous, right?

2022-04-04 13:59 UTC, Williangalvani approved these changes
looks good, but there's a typo in the commit msg

2022-04-04 14:28 UTC, patrickelectric commented
> looks good, but there's a typo in the commit msg

done.

2022-04-04 15:15 UTC, rafaellehmkuhl commented
Just tested. Everything working as expected.

2022-04-04 15:52 UTC, merged