core: beacon: remove blueos, add companion-wifi to mdns domains
bluerobotics/BlueOS-docker pull request #960
Opened 2022-04-06 13:55 UTC by Williangalvani

2022-04-06 13:59 UTC, patrickelectric requested changes

2022-04-06 13:59 UTC, patrickelectric commented on core/services/beacon/default-settings.json
> -        "domain_names": ["companion", "blueos", "blueos-wifi"],
`companion` is used temporarily for retrocompatibility and should be removed soon.
`companion.local` is also redirected to `blueos.local` to 'teache' the user that the new address should be used. The patch should only remove "blueos" from the wifi publishment.

2022-04-06 14:09 UTC, patrickelectric approved these changes

2022-04-06 14:09 UTC, merged

2023-10-17 20:08 UTC, patrickelectric commented
@Williangalvani do you remember why we removed it ?

2023-10-17 23:26 UTC, Williangalvani commented
> @Williangalvani do you remember why we removed it ?

yes. this was done in order to prevent connections from going through the wifi network instead of the wired one. which can happen if the same mdns address is broadcasted on both interfaces.