core: frontend: App: improve messages
bluerobotics/BlueOS-docker pull request #961
Opened 2022-04-06 14:28 UTC by joaoantoniocardoso

2022-04-06 14:31 UTC, patrickelectric reviewed
Thanks for the patch @joaoantoniocardoso but we are already late to create the 1.0.1 release, I'm happy to merge this PR after the review, but since you are changing the text a lot, I would also recommend to increase the number on `run_tour_version` for the next release.
Remember that you can test your changes with `yarn install && yarn serve`

2022-04-06 14:33 UTC, joaoantoniocardoso commented on core/frontend/src/App.vue
> +          you need anything else to improve your journey! Happy exploring!',
```suggestion
          content: `That's it! Now we want you to enjoy your experience with BlueOS! Also, don't forget to get in touch if
          you need anything else to improve your journey! Happy exploring!`,
```

2022-04-08 11:59 UTC, patrickelectric commented
@joaoantoniocardoso can you fix the PR ?

2022-04-08 13:53 UTC, patrickelectric requested changes
Can you squash your changes and rebase over master ?

2022-04-08 14:29 UTC, patrickelectric commented
> Thanks for the patch @joaoantoniocardoso but we are already late to create the 1.0.1 release, I'm happy to merge this PR after the review, but since you are changing the text a lot, I would also recommend to increase the number on `run_tour_version` for the next release. Remember that you can test your changes with `yarn install && yarn serve`

As requested, can you increase the `run_tour_version` number ?

2022-04-08 14:42 UTC, patrickelectric approved these changes

2022-04-08 15:13 UTC, merged